apiVersion: 1

datasources:
  - uid: timescaledb
    name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: factory
    user: factory
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    secureJsonData:
      password: factory
